final
miklealex/ITEA pull request #6
Opened 2021-06-17 22:32 UTC by alexprokopov1992

2021-06-23 18:39 UTC, miklealex requested changes

2021-06-23 18:39 UTC, miklealex commented on Bank/Bank/DataBase.h
> +            float totalRefill = 0;
Average per day means we need to calculate total transactions amount per each day and then calculate the average of those values.
Not just for today.

2021-06-23 18:39 UTC, miklealex commented on Bank/Bank/DataBase.h
> +                        biggest.resize(0);
clear() instead of resize(0)

2021-06-27 18:06 UTC, alexprokopov1992 commented on Bank/Bank/DataBase.h
> +            float totalRefill = 0;
Changed

2021-06-27 18:06 UTC, alexprokopov1992 commented on Bank/Bank/DataBase.h
> +                        biggest.resize(0);
changed

2021-06-27 18:07 UTC, closed without merging